// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGtNHi9lIYrfEZhPmO77-4fuyf_UpxQW4',
    appId: '1:711780700778:web:645ccab68efb096b02f013',
    messagingSenderId: '711780700778',
    projectId: 'aplicacion-enfermeria',
    authDomain: 'aplicacion-enfermeria.firebaseapp.com',
    storageBucket: 'aplicacion-enfermeria.firebasestorage.app',
    measurementId: 'G-PP59CEHKJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaYf4rTPXkQkJ98LuSTwpw6FRUK-pkjUc',
    appId: '1:711780700778:android:66345e89388e3dbf02f013',
    messagingSenderId: '711780700778',
    projectId: 'aplicacion-enfermeria',
    storageBucket: 'aplicacion-enfermeria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYA_cKec6T98F_w9tUSt311I055czuswo',
    appId: '1:711780700778:ios:e1dfe6c2a0dd48b502f013',
    messagingSenderId: '711780700778',
    projectId: 'aplicacion-enfermeria',
    storageBucket: 'aplicacion-enfermeria.firebasestorage.app',
    iosBundleId: 'com.example.appEnfermeria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYA_cKec6T98F_w9tUSt311I055czuswo',
    appId: '1:711780700778:ios:e1dfe6c2a0dd48b502f013',
    messagingSenderId: '711780700778',
    projectId: 'aplicacion-enfermeria',
    storageBucket: 'aplicacion-enfermeria.firebasestorage.app',
    iosBundleId: 'com.example.appEnfermeria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGtNHi9lIYrfEZhPmO77-4fuyf_UpxQW4',
    appId: '1:711780700778:web:55c9db41566535ff02f013',
    messagingSenderId: '711780700778',
    projectId: 'aplicacion-enfermeria',
    authDomain: 'aplicacion-enfermeria.firebaseapp.com',
    storageBucket: 'aplicacion-enfermeria.firebasestorage.app',
    measurementId: 'G-CZYK22G195',
  );
}
